export const DEFAULT_NOTES = [
  {
    id: '1',
    title: 'note 1',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Home',
    createdAt: new Date().toLocaleString(),
    description:
      'SOme useful note aosdfahsdfhaosdho aosjdfajsdoifjaosjdof aodjfioajsoidfjoiajsodifj aosdijf oasjdfioja oisdfo jasodifjoa jsdfoij aosdjfa[sodfjao[sdfjo jaosdifjoa oasjdif',
    updatedAt: null,
  },
  {
    id: '2',
    title: 'note 2',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Work',
    createdAt: new Date().toLocaleString(),
    description: 'SOme useful note',
    updatedAt: null,
  },
  {
    id: '3',
    title: 'note 3',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Vacation',
    createdAt: new Date().toLocaleString(),
    description: 'SOme useful note',
    updatedAt: null,
  },
  {
    id: '4',
    title: 'note 4',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Hobbie',
    createdAt: new Date().toLocaleString(),
    description: 'SOme useful note',
    updatedAt: null,
  },
  {
    id: '5',
    title: 'note 5',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Home',
    createdAt: new Date().toLocaleString(),
    description: 'SOme useful note',
    updatedAt: null,
  },
  {
    id: '6',
    title: 'note 6',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Vacation',
    createdAt: new Date().toLocaleString(),
    description: 'SOme useful note',
    updatedAt: null,
  },
  {
    id: '7',
    title: 'note 7',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Work',
    createdAt: new Date().toLocaleString(),
    description: 'SOme useful note',
    updatedAt: null,
  },
  {
    id: '8',
    title: 'note 8',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Home',
    createdAt: new Date().toLocaleString(),
    description: 'SOme useful note',
    updatedAt: null,
  },
  {
    id: '9',
    title: 'note 9',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Hobbie',
    createdAt: new Date().toLocaleString(),
    description: 'SOme useful note',
    updatedAt: null,
  },
  {
    id: '10',
    title: 'note 10',
    userEmail: 'zaqzaq@gmail.com',
    category: 'Work',
    createdAt: new Date().toLocaleString(),
    description: 'SOme useful note',
    updatedAt: null,
  },
];
